#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RAMWeex_Example' do
  pod 'RAMWeex', :path => '../'

  target 'RAMWeex_Tests' do
    inherit! :search_paths

    
  end
end
